### ISSUE TITLE
Failure to start Voltz

### ISSUE THREAD

**Issue by EttrionNano** [TechnicPack/TechnicLauncher#206] opened 2013-03-22 21:16 UTC
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 218

Stack Trace:
    Exception: EOFException
    Message: null
    Trace:
        java.util.zip.GZIPInputStream.readUByte(Unknown Source)
        java.util.zip.GZIPInputStream.readUShort(Unknown Source)
        java.util.zip.GZIPInputStream.readHeader(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        org.spoutcraft.diff.JBPatch.bspatch(JBPatch.java:94)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.patchMinecraft(MinecraftDownloadUtils.java:62)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:50)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_07 64 bit
    Total Memory: 176 MB
    Max Memory: 1820 MB
    Memory Free: 98 MB
    CPU Cores: 4

**Comment by JakDnB** [comment] 2013-03-22 22:05
Have same error and have tried all the following;
re-downloading launcher
deleting .technic folder and re-launching
updating java
deleting java cache

... still not working. wtf is the problem?

**Comment by Salynne** [comment] 2013-03-23 13:38
Duplicate of #202

**Closed as completed by Salynne** 2013-03-23 13:38 UTC
