### ISSUE TITLE
Technic Launcher Error Report

### ISSUE THREAD

**Issue by mlibbey** [TechnicPack/TechnicLauncher#452] opened 2014-01-31 04:17 UTC
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 393

```
Selected Pack: JAC's PixelSpark Pack
```

Stack Trace:
    Exception: RuntimeException
    Message: Minecraft not installed for this pack: InstalledPack{info=PlatformPackInfo{name='captainsparklez-survival-pack', displayName='JAC's PixelSpark Pack', url='http://192.95.32.85/pixelspark-technicuplink/PixelSparkV1.v-2.6.zip', icon=null, logo=net.technicpack.launchercore.restful.Resource@5ca801b0, background=net.technicpack.launchercore.restful.Resource@1a06f956, minecraft='1.6.4', forge='null', version='2.6', solder='', forceDir=false}, name='captainsparklez-survival-pack', platform=true, build='recommended', directory='%MODPACKS%\captainsparklez-survival-pack'}
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:191)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:74)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.9.1
    Operating System Architecture: x86_64
    Java version: 1.6.0_65 64 bit
    Total Memory: 95 MB
    Max Memory: 123 MB
    Memory Free: 23 MB
    CPU Cores: 8

**Comment by PristineOasis** [comment] 2014-02-05 23:08
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 395

```
Selected Pack: Ultra Modded-Survival
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.InstalledPack.loadCachedImage(InstalledPack.java:278)
        net.technicpack.launchercore.install.InstalledPack.loadImage(InstalledPack.java:263)
        net.technicpack.launchercore.install.InstalledPack.getLogo(InstalledPack.java:238)
        net.technicpack.launchercore.install.InstalledPack.hasLogo(InstalledPack.java:153)
        org.spoutcraft.launcher.skin.components.PackButton.setPack(PackButton.java:77)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:161)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:211)
        org.spoutcraft.launcher.skin.ModpackSelector.updatePack(ModpackSelector.java:118)
        net.technicpack.launchercore.install.AvailablePackList.triggerUpdateListeners(AvailablePackList.java:55)
        net.technicpack.launchercore.install.AvailablePackList$3$1.run(AvailablePackList.java:188)
        java.awt.event.InvocationEvent.dispatch(Unknown Source)
        java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.awt.EventQueue.access$200(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.run(Unknown Source)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 89 MB
    Max Memory: 727 MB
    Memory Free: 28 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment] 2014-02-06 08:01
mlibbey's bug is fixed in the latest beta
pristineoasis's bug is a dupe of #432

**Closed as completed by CannibalVox** 2014-02-06 08:01 UTC
