### ISSUE TITLE
Voltz Launch Error

### ISSUE THREAD

**Issue by TekkitFanatic** [TechnicPack/TechnicLauncher#359] opened 2013-11-30 22:44 UTC
Technic Launcher Error Report:

2.
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )

3.
    Launcher Build: 365

4.

5.
    Selected Pack: Tekkit Classic

6.
Stack Trace:

7.
    Exception: NullPointerException

8.
    Message: null

9.
    Trace:

10.
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:60)

11.
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:60)

12.

13.
System Information:

14.
    Operating System: Windows 7

15.
    Operating System Version: 6.1

16.
    Operating System Architecture: x86

17.
    Java version: 1.7.0_45 32 bit

18.
    Total Memory: 73 MB

19.
    Max Memory: 247 MB

20.
    Memory Free: 22 MB

21.
    CPU Cores: 4

create a new version of this paste RAW Paste Data

**Comment by CannibalVox** [comment] 2013-12-08 08:46
Closing this as a dupe of #356 - don't worry, I'm on the case!

**Closed as completed by CannibalVox** 2013-12-08 08:46 UTC
