### ISSUE TITLE
Java Runtime Environment error Mac

### ISSUE THREAD

**Issue by TheCodingGuy** [TechnicPack/TechnicLauncher#918] opened 2015-01-01 01:56 UTC
Hello!

All since Yosemite was released, I haven't been able to play vanilla MC.
Thats not really the problem here since that just keep say "You need Java Runtime 6" which I don't really feel like downloading.

This is the important problem:

I have been able to play Technic without problems with Java 7, until today....
Me and some family members were going to play some B-Team and they noticed a new launcher UI, I tried to open my Technic only to get a error message saying "You need to install Java Runtime Environment in order to display this web content". I thought this was quite odd and followed the "More info..." button which brought me to Oracle's download site for Java 8. 
I downloaded Java 8 to upgrade from 7, only to get the same message....
I tried a reboot witch didn't help much... 

The odd thing is that it's like Technic doesn't find my Java installation. Should I try re-download the launcher? Can this be done without deleting the modpacks respective saves, custom mods and configs?

I have found a <a href="https://discussions.apple.com/thread/6608589" target="_blank">page on the Apple discuss forums</a>, but it suggest to install Apples version of Java 6 on-top of 8 and that it will somehow work with both.

Thanks in advance and happy new year!

**Comment by CannibalVox** [comment] 2015-01-01 03:56
Hi- is this occurring when you attempt to run the jar version of the launcher?

**Comment by TheCodingGuy** [comment] 2015-01-01 13:18
Yes.

**Comment by TheCodingGuy** [comment] 2015-01-02 15:54
I'm so sorry for my impatience and I do understand that you are very busy, but is there any status of the issue yet?

**Comment by karolis1115** [comment] 2015-01-04 10:42
have you tryed to download the .exe verson file ?

**Comment by CannibalVox** [comment] 2015-01-04 10:54
That's not gonna work on the mac dogg.

**Comment by karolis1115** [comment] 2015-01-04 12:41
oh yeah sorry

**Comment by CannibalVox** [comment] 2015-01-04 12:42
Sorry TheCodingGuy that I've been so slow to respond here.  Could you open a command prompt and type java -version and tell me what it says?

**Comment by TheCodingGuy** [comment] 2015-01-04 12:58
Hi again CannibalVox, no problem. 

I tried to run java -version in Terminal(OS X command prompt) and I got a response telling me that i needed the Java JDK. Seemed quite odd to get that as a response I thought, but luckily I found the version via Javas control pane instead.
And it tells me that I'm running 1.8.0_25-b17, which is Version 8  Update 25  Build 17.

And on your site I saw that the OS X version is now a .zip file(not sure if this contains the .jar), but for Linux it's still a .jar file. When i downloaded Technic back in last spring, both OS X and Linux were .jar files. This might strengthen the "Re-install the launcher and download the new manually" theory?

**Comment by CannibalVox** [comment] 2015-01-04 13:07
That is really odd, but it seems like that could potentially be part of the problem.  Seems like your installation is jacked up.  Did you install it from the browser or did you download & install it offline?  Because browsers like to install java really weirdly if you let them.

**Comment by CannibalVox** [comment] 2015-01-04 13:09
Could be the "default" java installation your OS is trying to use could be missing or incomplete?  I'm afraid I'm not a mac user, so I'm kind of feeling my way around in the dark here.  But on Windows, java -version not working is a big red flag that java is not installed in a way that technic can use.

**Comment by TheCodingGuy** [comment] 2015-01-04 13:22
Hi again, yes it is really odd...
I'm quite sure I downloaded and installed it directly after I downloaded it from your site.
I guess that theres no other way than re-installing Technic... If thats not the problem, then I guess I need to re-install Java too. I'm getting back on this in a few hours when I return home.

**Comment by CannibalVox** [comment] 2015-01-04 13:23
Re-installing technic won't help.  I'd wipe java from your machine entirely and then start from scratch with a single install.

**Comment by CannibalVox** [comment] 2015-01-04 13:24
Well, you're a coding guy so I guess you might actually need multiple, so I guess nm.

**Comment by TheCodingGuy** [comment] 2015-01-04 15:28
The even more odd thing is that Java seems to work fine with etc web applications, it looks like Java doesn't even recognize the TechnicLauncher.jar.... 

This is a list that might explain certain things:

**Comment by TheCodingGuy** [comment] 2015-01-04 15:43
Hi again! As I'm back home, I shall order all the issues down here.

The even more odd thing is that Java seems to work fine with etc web applications, it looks like Java doesn't even recognize the TechnicLauncher.jar.... 

This is a list that might explain certain things:
1. It neither worked with Java 7 or 8
2. The only log that seemed to log the first launch after the update looks like this:

```
[B#439] 2015/01/01 02:21:26 [INFO] Args: []
[B#439] 2015/01/01 02:21:54 [INFO] Args: []
[B#439] 2015/01/01 02:28:38 [INFO] Args: []
[B#439] 2015/01/01 02:30:08 [INFO] Args: []
[B#439] 2015/01/01 02:36:07 [INFO] Args: []
[B#439] 2015/01/01 02:37:43 [INFO] Args: []
[B#439] 2015/01/01 02:48:13 [INFO] Args: []
[B#439] 2015/01/01 02:48:40 [INFO] Args: []
[B#439] 2015/01/01 23:14:31 [INFO] Args: []

```

And that is the only log after the update as it doesn't log anymore when I launch it... yes I do know certain languages in programming, unfortunately not in Java.. I'm not a expert reading Java logs but all the other logs from the old version is quite more different than this...

Are you sure the new update didn't break my launcher? 

If I'm forced to re-install Java and possibly the launcher, how do I wipe Technic FULLY from my computer? Is it just by removing the launcher.jar and the Technic folder inside application support?
Java is something I should manage to re-install though.

Terribly sorry for the long message and thank you so much for reading it!

UPDATE: I did some research about the problem, I see that many has the same issue. 
The odd thing is that it pops up every time they try to run a Java application.. It never happens to me except when I try to run the Technic launcher?

**Comment by karolis1115** [comment] 2015-01-04 16:18
same to me :(

**Comment by CannibalVox** [comment] 2015-01-04 17:07
"The even more odd thing is that Java seems to work fine with etc web applications"

That's because browsers keep their own version of java.  The question is, can you run other jars from the desktop.

"[B#439] 2015/01/01 02:21:26 [INFO] Args: []"

B#439 is the old launcher.  The current version of the launcher is back down to 210 or something (we've rolled over to v4).  So those logs predate your current version of Technic.  If it's saying you need the JDK/JRE then it's not going to log anything because our code has not yet run.

"Are you sure the new update didn't break my launcher?"

If it's saying java's not present, none of our code is executing so the version is largely irrelevant.

"If I'm forced to re-install Java and possibly the launcher, how do I wipe Technic FULLY from my computer? Is it just by removing the launcher.jar and the Technic folder inside application support?"

That's correct.  If you've installed the technic folder somewhere other than the default then you'll need to wipe BOTH the default folder and the one you chose, since we leave a file in the default folder pointing to the correct one (that is, unless you're set up for portable mode, but this was difficult to do in the old launcher and didn't really work properly- if you choose portable in the new launcher it will ONLY install to the location you choose).

"I did some research about the problem, I see that many has the same issue. 
The odd thing is that it pops up every time they try to run a Java application.. It never happens to me except when I try to run the Technic launcher?"

As I said, the status of java browser apps of working/not working is basically irrelevant because browser java is siloed off on its own.  It can work/not work entirely separately from desktop java.

**Comment by TheCodingGuy** [comment] 2015-01-04 17:57
> That's correct. If you've installed the technic folder somewhere other than the default then you'll need to wipe BOTH the default folder and the one you chose, since we leave a file in the default folder pointing to the correct one (that is, unless you're set up for portable mode, but this was difficult to do in the old launcher and didn't really work properly- if you choose portable in the new launcher it will ONLY install to the location you choose).

I just took a look inside the settings.json file, and it looks like I chose the default back in April when I installed this. 

If I'm correct now and according to your info, I should just remove my launcher.jar and the folder inside application support and then head over to http://www.technicpack.net/download and re-download the launcher?

Please correct me if I missed any info. 

> That's because browsers keep their own version of java. The question is, can you run other jars from the desktop.

I tried to run some .jar files of my desktop which brought up a security window based on my settings and NOT a JRE or JDK error, which it's a good sign that my Java installation mustn't be corrupt?

Thanks again for the useful info!

**Comment by CannibalVox** [comment] 2015-01-04 18:03
- That's correct
- If you're seeing a security window, it hasn't actually tried to run it yet.

**Comment by CannibalVox** [comment] 2015-01-04 18:04
The security window tells you the same thing that the error window does- that OSX recognizes that it's supposed to be running java when you click on that file.

**Comment by TheCodingGuy** [comment] 2015-01-04 18:58
Hi again, I tried to re-install it. 
But I only managed to click "install" via the installation window only to recive the same message...
Do you think that OS X 10.10 or 10.10.1 might have something to do with it? 
I hear a lot that Apple blocks certain Java versions, but as far as I know Java 8 is fine.

Another odd thing is that the installation was executed...

**Comment by CannibalVox** [comment] 2015-01-04 19:03
Wait, it displayed our installation window?

**Comment by CannibalVox** [comment] 2015-01-04 19:04
Can you hit me with some screenshots?  The whole process and the final error?

**Comment by TheCodingGuy** [comment] 2015-01-04 19:38
This is the install(Note: I was NOT going to install the portable version):

<img src="http://i.imgur.com/SlCJ2Qt.png"><img>

The error: 

<img src="http://i.imgur.com/YdvTJjK.png"><img>
(Sorry for the error that is in swedish, I shall translate it)
<b> "You must install Java Runtime in order to display this web content"</b>
"Click on "More info..." to visit and download Java Runtime Environment"

**Comment by CannibalVox** [comment] 2015-01-04 19:55
This is the most astonishing thing I've ever seen.  Is there anything in the logs?

**Comment by TheCodingGuy** [comment] 2015-01-04 20:07
Yes, what i see theres only a "settings.json" and a log folder containing this:

**Comment by TheCodingGuy** [comment] 2015-01-04 20:11
Yes, what i see theres only a "settings.json" and a log folder containing this:

```
[B#211] 2015/01/04 21:05:57 [INFO] Console Mode Activated
[B#211] 2015/01/04 21:05:57 [INFO] Launching command: 'java -Xmx256m - Djava.net.preferIPv4Stack=true -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -cp /Users/MyUsername/Desktop/Technic/TechnicLauncher.jar net.technicpack.launcher.LauncherMain '
```

Sorry for no new lines.

UPDATE: I just looked in Java's control panel and tried to see what programs that was listed in the JREs settings... I did NOT found any name referring to Technic...

**Comment by CannibalVox** [comment] 2015-01-04 20:15
Ah HA!

So here's what's up.  Mac knows where to find java.  It finds it just fine.  But technic issues the console command "java" under all kinds of circumstances: to make sure it's running under IPV4 mode, to execute updates, to launch minecraft.  So you can run Technic initially no problem, but the console command "java" is not working, so technic can't do all kinds of stuff.

So for some reason java is not available to technic from the console where it's at- once you fix that, technic will work.

This could be something as simple as a permissions issue, or maybe something more complicated.  If you were on windows I'd tell you to make sure java's in your PATH, but you're not so.

**Comment by TheCodingGuy** [comment] 2015-01-04 20:20
> So for some reason java is not available to technic from where it's at- once you fix that, technic will work.

Alright, do you mean physical location or a file path in that manner?
Glad that that issue seems to be fixed in the near future!

**Comment by CannibalVox** [comment] 2015-01-04 20:23
What happens if, in a command line interface, you hit echo $PATH | less

**Comment by GenPage** [comment] 2015-01-04 20:39
I ran into another Mac user on the IRC last night that had the same issue. (Mac OS X Yosemite) 

This was resolved by installing the JDK not the JRE. Not sure if you want to install the whole development kit, or the fact that it just possibly overwrote the java_home env when installing. 

http://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by CannibalVox** [comment] 2015-01-04 20:40
I don't think it's java_home, I think it's the path.  The fact that it actually appends to the path.

**Comment by TheCodingGuy** [comment] 2015-01-04 21:37
> What happens if, in a command line interface, you hit echo $PATH | less

I just wanna double check here, Do you mean Terminal?

> I ran into another Mac user on the IRC last night that had the same issue. (Mac OS X Yosemite)
> This was resolved by installing the JDK not the JRE. Not sure if you want to install the whole development kit, or the fact that it just possibly overwrote the java_home env when installing.
> http://www.oracle.com/technetwork/java/javase/downloads/index.html
> 
> I don't think it's java_home, I think it's the path. The fact that it actually appends to the path.

The odd thing was that the environment variables for Java seemed to be correct before 10.10.1(Pretty sure I was playing B-team after 10.10, but I might be wrong as it has felt like time is flying by), they could have been reseted or wiped with the update?

I am not quite sure <a href="http://www.ntu.edu.sg/home/ehchua/programming/howto/Environment_Variables.html">if this is helpful</a>, but i'll leave it here just in case.

**Comment by CannibalVox** [comment] 2015-01-04 21:49
That's right, I meant terminal.

**Comment by TheCodingGuy** [comment] 2015-01-04 22:32
Alright, I get this in return:

```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by CannibalVox** [comment] 2015-01-04 22:36
What folder is java in?

**Comment by TheCodingGuy** [comment] 2015-01-04 23:15
Hm.. As of my knowledge my Java seems to be installed here:

```
/usr/bin/java
```

But I have seen this file come up when etc vanilla MC or Technic or probably any other Java application makes a firewall request.

**Comment by CannibalVox** [comment] 2015-01-04 23:19
So try this:

export JAVA_HOME=/usr/bin/java

And if that doesn't make technic work

export PATH=/usr/bin/java:$PATH

**Comment by TheCodingGuy** [comment] 2015-01-05 00:16
Hello again, I'm sorry to announce that I can't be online for a few hours as I'm going to bed.
I will try to run the command ASAP tomorrow.

One thing that I found odd is the message from my tries to execute "java -version" in Terminal...
I will post the image here:

<img src="http://i.imgur.com/eD5ZwdC.png"></img>

Translation: 

<b>If you want to use "java" -commandlinetool you must install a JDK.</b>
Click on "More info....." to visit the website in order to download Java Developer Kit.

Is this also not working because of the non-working environment variables?
Or does this have something that might have to do with @GenPage post?

**Comment by CannibalVox** [comment] 2015-01-05 00:53
Wow uhhhh.... that sure is a thing.  I have no idea how that would work or even be possible, how does anything run at all.

Definitely try the two things I named but there's a very real possiiblity neither will work and installing the JDK is the next step.

**Comment by TheCodingGuy** [comment] 2015-01-05 20:43
Hi again and so sorry about the delay.

Are you sure it's "export JAVA_HOME=/usr/bin/java" or export PATH=/usr/bin/java:$PATH?

The reason why I'm asking is because I don't wanna mess something up with the variables and then the environment path is even more lost....

**Comment by CannibalVox** [comment] 2015-01-05 20:47
Provided that "java" is in /usr/bin/java that is correct.

**Comment by TheCodingGuy** [comment] 2015-01-06 13:57
Hi again and sorry for the late respond!

I haven't been able to get on my computer today, and I have a question:
I looked around to see what the command for displaying the Java enviroment path, and the ones I tried responded with errors... 
Am I typing the wrong command or is the Java path that broken?

Thanks again!

**Comment by CannibalVox** [comment] 2015-01-06 18:33
echo $PATH for your OS's environment path.  Java doesn't have one.

**Comment by TheCodingGuy** [comment] 2015-01-07 17:06
Hello! 
Much have happened this week due school starts again tomorrow, so I haven't been able to get much done..

I just found my java_home in "/usr/libexec/java_home", <a href="https://developer.apple.com/library/mac/qa/qa1170/_index.html" target="_blank">according to Apple</a> It should be there.. 

Should I try to post on Stackoverflow and see if anyone there knows why no Java command can be executed even though the JRE is installed?

Thank you once again for taking time to read and solve this!

**Comment by Bo98** [comment] 2015-01-15 14:59
`/usr/bin/java` only gets replaced when the JDK is installed. Oracle's JRE java is at `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java`. I don't know why Oracle decided to not replace `/usr/bin/java` in JRE. When Apple updated Java 6/1.6 for OS X there wasn't different JRE and JDK options so it didn't happen then.

**Comment by CannibalVox** [comment] 2015-01-30 19:49
I'm not sure where this ended up, but please comment with your status if you'd like this to be re-opened.

**Closed as completed by CannibalVox** 2015-01-30 19:49 UTC

**Comment by XBlackLeopardX** [comment] 2015-04-11 04:42
I can confirm that installing the Java JDK for java 7 or up does let the launcher access java 7 or up through the java tab in the launcher options i just tested it with a friend who has a mac

so for mods like HardcoreEnderExpansion which require java 7 and up to work if you dont do this or whatever else to let the launcher access the correct java the game will just crash while starting up
