### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by The4D6** [TechnicPack/TechnicLauncher#228] opened 2013-03-31 17:40 UTC
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 221

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.technic.rest.RestAPI.shouldUsePatch(RestAPI.java:343)
        org.spoutcraft.launcher.technic.rest.RestAPI.getMinecraftMD5(RestAPI.java:326)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:45)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_01 64 bit
    Total Memory: 180 MB
    Max Memory: 1360 MB
    Memory Free: 89 MB
    CPU Cores: 8

Help? I don't know what to do

**Comment by Salynne** [comment] 2013-03-31 17:44
Duplicate of #212 this is resolved but the auto updater isn't working. Try downloading again from www.technicpack.net/download in the meantime.

**Closed as completed by Salynne** 2013-03-31 17:44 UTC
