### ISSUE TITLE
Launcher crashes when I try to launch a modpack

### ISSUE THREAD

**Issue by noahkra** [TechnicPack/TechnicLauncher#399] opened 2013-12-18 20:22 UTC
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 377

```
Selected Pack: BlockyConomyPack2
```

Stack Trace:
    Exception: RuntimeException
    Message: Minecraft not installed for this pack: InstalledPack{info=PlatformPackInfo{name='blockyconomiepack', displayName='BlockyConomyPack2', url='https://dl.dropboxusercontent.com/u/***.zip', icon=null, logo=net.technicpack.launchercore.restful.Resource@75240d4a, background=net.technicpack.launchercore.restful.Resource@11e4b15b, minecraft='1.6.4', forge='null', version='1.0.3', solder='', forceDir=false}, name='blockyconomiepack', platform=true, build='recommended', directory='%MODPACKS%\blockyconomiepack'}
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:174)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

System Information:
    Operating System: Windows Vista
    Operating System Version: 6.0
    Operating System Architecture: amd64
    Java version: 1.7.0_40 64 bit
    Total Memory: 122 MB
    Max Memory: 1810 MB
    Memory Free: 75 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment] 2013-12-24 06:49
This is a dupe of #395, please post your info there.

**Closed as completed by CannibalVox** 2013-12-24 06:49 UTC
