### ISSUE TITLE
Menus completely useless

### ISSUE THREAD

**Issue by ryanvade** [TechnicPack/TechnicLauncher#1071] opened 2015-02-08 05:32 UTC
![workspace 1_052](https://cloud.githubusercontent.com/assets/1910293/6095401/79766c10-af21-11e4-9e91-a089457e5820.png)
Like the photo shows.  The menus are completely useless.  The modpack settings window never opens, the loginscreen is the same grey blank.  Completely broken.

**Comment by CannibalVox** [comment] 2015-02-08 16:14
Gnome 3 basically doesn't work with undecorated java windows.  I'd recommend using something else just like, in general.

**Comment by CannibalVox** [comment] 2015-02-08 16:38
I'm actually not 100% sure that it's gnome3 specifically but repaint fails for java has been a problem for some shells/windows managers for many years now- http://ossowicki.com/?p=155

**Comment by CannibalVox** [comment] 2015-02-08 16:39
Another possible solution: https://bbs.archlinux.org/viewtopic.php?id=159016

**Comment by ryanvade** [comment] 2015-02-08 17:34
This is NOT just Gnome 3. It also happens on KDE, LXDE, XFCE...I have tried them all.  

NOT CLOSED

**Comment by CannibalVox** [comment] 2015-02-08 17:36
Yeah, it is.  Ubuntu/unity/compiz has been confirmed working with both oracle & openjdk.  Additionally, there is a lot of writing about bugs in various shells/window managers causing your exact issue.  I've posted some possible solutions, but it's up to you to get your setup working.

**Comment by ryanvade** [comment] 2015-02-08 17:39
CannibalVox this sorta works
_JAVA_AWT_WM_NONREPARENTING=1; export _JAVA_AWT_WM_NONREPARENTING

**Comment by ryanvade** [comment] 2015-02-08 17:42
This is not over

**Comment by ghost** [comment] 2015-02-08 20:14
@ryanvade, are you running an nvidia card with the proprietary drivers? I get this behavior as well, but my laptop with intel graphics has no issues. I think this might be an nvidia issue. Nvidia has been plagued with repainting issues for some time now.  In any case, setting that environment variable did not work for me on my nvidia desktop.

@CannibalVox, please consider that not everyone runs unity - I realize you cannot support every fringe WM but Compiz is only one part of the ecosystem. If this is indeed not your bug I understand closing the report but we're not sure that's the case at the moment.

@ryanvade, please try to keep it civil - returning an attitude is not the solution if someone is behaving contrary to what you'd like.

**Comment by CannibalVox** [comment] 2015-02-08 20:18
ryanvade was blocked because he went on a ticket-opening spree

We've already had this bug reported and investigated and ultimately it was not on our end. We are open source if you'd like to perform your own investigation, but in our experience users who encounter this issues also have it with a SSCCE that simply creates a JFrame without decorations.

**Closed as completed by CannibalVox** 2015-02-08 20:18 UTC

**Comment by ghost** [comment] 2015-02-08 20:21
I see - might I suggest that this response might have been a better initial reply than the passive-aggressive tone? Doing some basic research, this seems to be an issue with java itself, with bug reports being opened since the days of Sun.

In any case, thanks for your work on Technic.
