### ISSUE TITLE
Technic Launcher Error Report

### ISSUE THREAD

**Issue by cstdenis** [TechnicPack/TechnicLauncher#424] opened 2014-01-10 02:14 UTC
Got this error from the launcher. Ran it again and it works fine. 

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 383

```
Selected Pack: Lapito's Galacticraft Modpack
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.InstalledPack.loadCachedImage(InstalledPack.java:278)
        net.technicpack.launchercore.install.InstalledPack.loadImage(InstalledPack.java:263)
        net.technicpack.launchercore.install.InstalledPack.getBackground(InstalledPack.java:343)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:118)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
        org.spoutcraft.launcher.Launcher.refreshPack(Launcher.java:258)
        net.technicpack.launchercore.install.InstalledPack$1.run(InstalledPack.java:314)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_05 64 bit
    Total Memory: 244 MB
    Max Memory: 3621 MB
    Memory Free: 161 MB
    CPU Cores: 8

**Comment by CannibalVox** [comment] 2014-02-06 07:51
Closing as dupe of #396.

**Closed as completed by CannibalVox** 2014-02-06 07:51 UTC
