### ISSUE TITLE
Unexpected Error!

### ISSUE THREAD

**Issue by hornet-catcher** [TechnicPack/TechnicLauncher#403] opened 2013-12-20 20:25 UTC
Stack Trace:
    Exception: RuntimeException
    Message: Minecraft not installed for this pack: InstalledPack{info=SolderPackInfo{name='hexxit', display_name='Hexxit', url='null', icon_md5='fb51fd408d5d3bc7eba8d9a820ab555c', logo_md5='1426f5b19df42eab2cabbaa34823c8c9', background_md5='a99b0c0eb00ac657d29eb9e1f9086033', recommended='1.0.10', latest='1.0.10', builds=[1.0.0, 1.0.1, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10], solder=net.technicpack.launchercore.restful.solder.Solder@1dbf9c3}, name='hexxit', platform=false, build='recommended', directory='%MODPACKS%\hexxit'}
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:174)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

**Comment by CannibalVox** [comment] 2013-12-24 06:48
This is a dupe of #395, please post your info there.

**Closed as completed by CannibalVox** 2013-12-24 06:48 UTC
