### ISSUE TITLE
Tekkit Classic Launch Error

### ISSUE THREAD

**Issue by Weahut** [TechnicPack/TechnicLauncher#360] opened 2013-12-02 20:28 UTC
41 mods loaded
Optifine OptiFine_1.2.5_HD_S_C6
Minecraft Forge 3.3.8.164
FML v2.2.106.176
Forge Mod Loader version 2.2.106.176 for Minecraft 1.2.5
    mod_CodeChickenCore : Post-initialized (modpack.jar)
    mod_MinecraftForge : Post-initialized (modpack.jar)
    mod_NotEnoughItems : Post-initialized (modpack.jar)
    mod_ReiMinimap : Post-initialized ([1.2.5]ReiMinimap_v3.2_04.zip)
    mod_IC2 : Post-initialized (industrialcraft-2-client_1.97.jar)
    mod_IC2AdvancedMachines : Post-initialized (AdvancedMachines_4.0_client.zip)
    mod_BuildCraftCore : Post-initialized (buildcraft-client-A-core-2.2.14.zip)
    mod_BuildCraftBuilders : Post-initialized (buildcraft-client-B-builders-2.2.14.zip)
    mod_BuildCraftEnergy : Post-initialized (buildcraft-client-B-energy-2.2.14.zip)
    mod_BuildCraftFactory : Post-initialized (buildcraft-client-B-factory-2.2.14.zip)
    mod_BuildCraftTransport : Post-initialized (buildcraft-client-B-transport-2.2.14.zip)
    mod_AdditionalPipes : Post-initialized (buildcraft-client-DA-additionalpipes-2.1.3.zip)
    mod_ComputerCraft : Post-initialized (ComputerCraft)
    mod_RedPowerMachine : Initialized (RedPowerMachine-2.0pr5b2.zip)
    mod_ccSensors : Initialized (ccSensors-client-MC125-B017pr1.zip)
    mod_CCTurtle : Initialized (ComputerCraft)
    mod_EE : Initialized (EE2ClientV1.4.6.5.jar)
    mod_EnderStorage : Initialized (EnderStorage-Client 1.1.3.zip)
    mod_IC2NuclearControl : Initialized (IC2NuclearControl_client_v1.1.10b.zip)
    mod_ImmibisCore : Initialized (immibis-core_49.1.1_for_1.2.5-client.jar)
    mod_InvTweaks : Initialized (InvTweaks-1.41b-1.2.4.zip)
    mod_MAtmos_forModLoader : Initialized (MAtmos_packaged.zip)
    mod_ModularForceFieldSystem : Initialized (mffs_rev7_for_1.2.5-client.zip)
    mod_IC2_ChargingBench : Initialized (mod_chargingbench-client-1.95b-1.2.5-r1.zip)
    mod_CompactSolars : Initialized (mod_compactsolars-client-2.3.2.10.zip)
    mod_IronChest : Initialized (mod_ironchests-client-3.8.0.40.zip)
    mod_RedPowerCore : Initialized (RedPowerCore-2.0pr5b2.zip)
    mod_NetherOres : Initialized (NetherOres_Client_1.2.1.zip)
    mod_PowerConverters : Initialized (PowerConverters_Client_1.3.4.zip)
    mod_Railcraft : Initialized (Railcraft_Client_5.3.3.zip)
    mod_RedPowerControl : Initialized (RedPowerControl-2.0pr5b2.zip)
    mod_RedPowerLighting : Initialized (RedPowerLighting-2.0pr5b2.zip)
    mod_RedPowerLogic : Initialized (RedPowerLogic-2.0pr5b2.zip)
    mod_RedPowerWiring : Initialized (RedPowerWiring-2.0pr5b2.zip)
    mod_RedPowerWorld : Initialized (RedPowerWorld-2.0pr5b2.zip)
    mod_TubeStuff : Initialized (tubestuff_49.1.2_for_1.2.5-client.jar)
    Balkon's WeaponMod : Initialized (WeaponMod.zip)
    mod_WirelessRedstoneCore : Initialized (WR-CBE Core-Client 1.2.2.3.zip)
    mod_WirelessRedstoneAddons : Initialized (WR-CBE Addons-Client 1.2.2.3.zip)
    mod_WirelessRedstoneRedPower : Initialized (WR-CBE RedPower-Client 1.2.2.1.zip)
    mod_ImmiChunkLoaders : Initialized (zdimensional-anchor_rev3.2_for_1.2.5-client.jar)

```
  Minecraft has crashed!      
  ----------------------      
```

Minecraft has stopped running because it encountered a problem.

--- BEGIN ERROR REPORT d9132588 --------
Generated 12/2/13 3:20 PM

Minecraft: Minecraft 1.2.5
OS: Windows 7 (x86) version 6.1
Java: 1.7.0_25, Oracle Corporation
VM: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
LWJGL: 2.9.0
OpenGL: Intel(R) HD Graphics 3000 version 3.1.0 - Build 9.17.10.2867, Intel

java.lang.RuntimeException: RedPowerCore: BlockID 140 occupied by powercrystals.netherores.BlockNetherOres, autoAssign is disabled.
    at forge.MinecraftForge.killMinecraft(MinecraftForge.java:476)
    at eloraam.core.Config.getBlockID(Config.java:114)
    at RedPowerWorld.initialize(RedPowerWorld.java:479)
    at mod_RedPowerWorld.initialize(mod_RedPowerWorld.java:37)
    at mod_RedPowerMachine.initialize(mod_RedPowerMachine.java:57)
    at mod_RedPowerMachine.modsLoaded(mod_RedPowerMachine.java:25)
    at cpw.mods.fml.common.modloader.ModLoaderModContainer.postInit(ModLoaderModContainer.java:362)
    at cpw.mods.fml.common.Loader.postModInit(Loader.java:290)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:629)
    at cpw.mods.fml.client.FMLClientHandler.onLoadComplete(FMLClientHandler.java:223)
    at net.minecraft.client.Minecraft.a(Minecraft.java:429)
    at net.minecraft.client.Minecraft.run(Minecraft.java:738)
    at java.lang.Thread.run(Unknown Source)
--- END ERROR REPORT 84592d97 ----------

**Comment by CannibalVox** [comment] 2013-12-02 20:29
Looks like you jacked with some config files.  This is tekkit classic, right?

**Comment by Weahut** [comment] 2013-12-02 20:29
Yes it is, this is my girlfriends laptop, I know she hasn't messed with anything, nor have I

**Comment by CannibalVox** [comment] 2013-12-02 20:30
Well, I'm pretty sure tekkit classic doesn't have any block ID conflicts when correctly installed, since it hasn't been modified in over a year, so....

**Comment by CannibalVox** [comment] 2013-12-02 20:31
Make sure you're using the recommended version, not the latest version, and if the problem persists, delete your .technic/modpacks/tekkit folder and reinstall.

**Comment by Weahut** [comment] 2013-12-02 20:32
Just saying, she doesn't know how to do anything with any files.  Also I had her reinstall completely new, it is using recommended as suggested as well.

**Comment by abalabahaha** [comment] 2013-12-03 22:04
Did you click on the pack settings and reset? NetherOres should have block ID 135 for ores.

**Comment by Weahut** [comment] 2013-12-04 00:08
No I haven't tried that yet.  It keeps failing to re install in the first place now

**Comment by abalabahaha** [comment] 2013-12-04 00:15
That's another problem. What's happening? Is it not downloading?

**Comment by Weahut** [comment] 2013-12-04 00:38
Its finally working, but then she kept getting disconnected a bunch of times and now she can't log in, it gives me,

Stack Trace:
      Exception:  NullPointerException
      Message:  null
      Trace:
            net.technicpack.launcher.launchercore.install.ModpackInstaller.installPacl(ModpackInstaller.java:60)
            org.spoutcraft.launcher.InstallThread.run(InstallThread.java:60)

I reset the whole pack and that's what I get when I try to start it again as well

**Comment by Weahut** [comment] 2013-12-04 00:41
Sorry that isn't copy/pasted, I am on my desktop and I am just reading off her laptop

**Comment by abalabahaha** [comment] 2013-12-04 00:42
Have you tried waiting around half a minute, then downloading?

**Comment by Weahut** [comment] 2013-12-04 00:50
Yeah I have waited a few minutes before trying again

**Comment by abalabahaha** [comment] 2013-12-04 00:57
Like opening it then waiting a few minutes then downloading.

**Comment by Weahut** [comment] 2013-12-04 01:33
I guess it is working now again.  Hopefully it continues to work!

**Comment by CannibalVox** [comment] 2013-12-05 08:58
The newer error you received is a duplicate of another issue we're working on now, so I'm gonna go ahead and close this.

**Closed as completed by CannibalVox** 2013-12-05 08:58 UTC

**Comment by destroyrenumber2** [comment] 2014-03-12 19:57
guyss a new error , i have one plz help i posted it
