### ISSUE TITLE
Can't load Voltz Pack

### ISSUE THREAD

**Issue by hillmand** [TechnicPack/TechnicLauncher#204] opened 2013-03-22 20:30 UTC
Stack Trace:
    Exception: EOFException
    Message: null
    Trace:
        java.util.zip.GZIPInputStream.readUByte(Unknown Source)
        java.util.zip.GZIPInputStream.readUShort(Unknown Source)
        java.util.zip.GZIPInputStream.readHeader(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        org.spoutcraft.diff.JBPatch.bspatch(JBPatch.java:94)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.patchMinecraft(MinecraftDownloadUtils.java:62)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:50)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

Get this error when trying to launch Voltz from the launcher

**Comment by Salynne** [comment] 2013-03-23 13:37
Duplicate of #202

**Closed as completed by Salynne** 2013-03-23 13:37 UTC
