### ISSUE TITLE
Error When Trying to Start TechnicLauncher

### ISSUE THREAD

**Issue by p4ck3ts3nd3r** [TechnicPack/TechnicLauncher#464] opened 2014-02-04 13:34 UTC
When I try to double-click the TechnicLauncher.jar to start, nothing seems to happen. When I try to launch via Terminal, I get this:

p**********_@p**_********-PC:~/Games$ java -jar TechnicLauncher.jar
Feb 04, 2014 8:05:25 AM org.spoutcraft.launcher.entrypoint.Start launch
INFO: Args: []
The program 'java' received an X Window System error.
This probably reflects a bug in the program.
The error was 'RenderBadPicture (invalid Picture parameter)'.
  (Details: serial 2284 error_code 143 request_code 139 minor_code 6)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

What is this exactly, and how can I fix it?

**Comment by PristineOasis** [comment] 2014-02-05 23:07
Mine did that too. This was the log.

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 395

```
Selected Pack: Ultra Modded-Survival
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.InstalledPack.loadCachedImage(InstalledPack.java:278)
        net.technicpack.launchercore.install.InstalledPack.loadImage(InstalledPack.java:263)
        net.technicpack.launchercore.install.InstalledPack.getLogo(InstalledPack.java:238)
        net.technicpack.launchercore.install.InstalledPack.hasLogo(InstalledPack.java:153)
        org.spoutcraft.launcher.skin.components.PackButton.setPack(PackButton.java:77)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:161)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:211)
        org.spoutcraft.launcher.skin.ModpackSelector.updatePack(ModpackSelector.java:118)
        net.technicpack.launchercore.install.AvailablePackList.triggerUpdateListeners(AvailablePackList.java:55)
        net.technicpack.launchercore.install.AvailablePackList$3$1.run(AvailablePackList.java:188)
        java.awt.event.InvocationEvent.dispatch(Unknown Source)
        java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.awt.EventQueue.access$200(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.run(Unknown Source)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 89 MB
    Max Memory: 727 MB
    Memory Free: 28 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment] 2014-02-06 08:07
p4ck3ts3nd3r, you probably need to install java

PristineOasis, your error is nothing like p4ck3ts3nd3r's, and is a dupe of #432

**Closed as completed by CannibalVox** 2014-02-06 08:07 UTC

**Comment by p4ck3ts3nd3r** [comment] 2014-02-06 08:36
Are you kidding me? I'm not an idiot. This is not a matter of whether I
have Java installed. There is a bug in the launcher.

**Comment by CannibalVox** [comment] 2014-02-06 08:38
Oh, okay, bug in the launcher causing OS-level errors on your box.  Not a misconfigured operating system or java install.  Got it.

**Comment by p4ck3ts3nd3r** [comment] 2014-02-06 08:42
Apparently you didn't actually read the log, otherwise you would have seen that it wasn't the same as #432. Please read logs before you jump to conclusions.

**Comment by CannibalVox** [comment] 2014-02-06 08:43
Log from here:

Stack Trace:
Exception: NullPointerException
Message: null
Trace:
net.technicpack.launchercore.install.InstalledPack.loadCachedImage(InstalledPack.java:278)
net.technicpack.launchercore.install.InstalledPack.loadImage(InstalledPack.java:263)
net.technicpack.launchercore.install.InstalledPack.getLogo(InstalledPack.java:238)
net.technicpack.launchercore.install.InstalledPack.hasLogo(InstalledPack.java:153)
org.spoutcraft.launcher.skin.components.PackButton.setPack(PackButton.java:77)
org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:161)
org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:211)
org.spoutcraft.launcher.skin.ModpackSelector.updatePack(ModpackSelector.java:118)

Log from #432:

Stack Trace:
Exception: NullPointerException
Message: null
Trace:
net.technicpack.launchercore.install.InstalledPack.loadCachedImage(InstalledPack.java:278)
net.technicpack.launchercore.install.InstalledPack.loadImage(InstalledPack.java:263)
net.technicpack.launchercore.install.InstalledPack.getLogo(InstalledPack.java:238)
org.spoutcraft.launcher.skin.components.PackButton.setPack(PackButton.java:72)
org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:151)
org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
org.spoutcraft.launcher.Launcher.refreshPack(Launcher.java:258)
net.technicpack.launchercore.install.InstalledPack$1.run(InstalledPack.java:314)

Totally different, nothing in common, got it.

**Comment by p4ck3ts3nd3r** [comment] 2014-02-06 23:51
No dumbass, this was my log: p**********_@p**_********-PC:~/Games$ java -jar TechnicLauncher.jar
Feb 04, 2014 8:05:25 AM org.spoutcraft.launcher.entrypoint.Start launch
INFO: Args: []
The program 'java' received an X Window System error.
This probably reflects a bug in the program.
The error was 'RenderBadPicture (invalid Picture parameter)'.
(Details: serial 2284 error_code 143 request_code 139 minor_code 6)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the --sync command line
option to change this behavior. You can then get a meaningful
backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by CannibalVox** [comment] 2014-02-06 23:51
You need to read more carefully.

**Comment by p4ck3ts3nd3r** [comment] 2014-02-06 23:52
If the launcher won't even run, I can't get a "Null Pointer Exception" error, now can I?

**Comment by CannibalVox** [comment] 2014-02-06 23:53
You need to read more carefully.

**Comment by CannibalVox** [comment] 2014-02-06 23:53
Start at the beginning of the task, and read everything.

**Comment by p4ck3ts3nd3r** [comment] 2014-02-07 00:05
Look at the timestamps. When I got the Null Pointer Exception was well
after I DID get it to start (when it sat idle for more than 30 - 60
minutes. So you go back and review the log.

**Comment by CannibalVox** [comment] 2014-02-07 00:06
Are you stupid or something?  Go back and read it again.  Eventually you'll be able to understand the conversation that occurred here.

**Comment by p4ck3ts3nd3r** [comment] 2014-02-07 00:20
I think you have the issue. The only error that I made a reference to on this topic, had to do with a 'RenderBadPicture (invalid Picture parameter)'. Now, PristineOasis had a different error, but that wasn't me.

**Comment by CannibalVox** [comment] 2014-02-07 00:20
Okay, you're halfway there!  Now, who was I addressing when I said their log was a dupe of #432?

**Comment by CannibalVox** [comment] 2014-02-07 00:21
(You can find this out by reading the text of my comment!)

**Comment by p4ck3ts3nd3r** [comment] 2014-02-07 00:29
Did you forget this comment I made?:
Are you kidding me? I'm not an idiot. 

This is not a matter of whether I have Java installed. There is a bug in the launcher.
…

I KNOW that I have Java installed. Don't try to act like I'm an idiot. You are the one that tried to say that I said something else. 

Before you try to make a smartass remark at somebody, make sure YOU read carefully.

**Comment by CannibalVox** [comment] 2014-02-07 00:30
I see you are not chastened by the fact that we just had a 16 hour exchange whose main feature was your illiteracy.

**Comment by CannibalVox** [comment] 2014-02-07 00:31
Okay, fine, let's read the error message.  Oh, it's your operating system telling you there's probably a bug in java.exe.  Well you say you have it installed, what else might cause a bug in java.exe?  Hm, let me think about it.

You wouldn't happen to have installed a java 1.8 beta, which contains bugs, because it's a beta, and then when your operating system told you that the program you just ran contained bugs, which you knew, come crying to me?  You wouldn't do that, would you?

**Comment by p4ck3ts3nd3r** [comment] 2014-02-07 00:55
Lmao... You just proved my point... First of all, I don't have a "java.exe", I'm running Linux. Second, I tried running with java 1.7 as well (I still got the same response). So, like I said before, READ before you jump to conclusions... Dumbass. Oh btw, I hope you have a WONDERFUL day! :P Love you. XD

**Comment by vorburger** [comment] 2014-08-16 09:28
Aloha @p4ck3ts3nd3r + @CannibalVox - I also just hit "this" problem (as in that "'RenderBadPicture" X Window error from issue descriptions - I'm simply ignoring all troll comments between that and this) - and in the public interest of anyone else hitting this page from Googling and more interested in a solution than in the yelling, here's the technical background:

This is (obviously, note "an X Window System error")  a Linux specific issue. It can happen on Java 8, Java 7, JDK/JRE, OpenJDK or Oracle's... it's not specific to TechnicLauncher (or Minecraft) - just Google for "'java' received an X Window System error.  'RenderBadPicture (invalid Picture parameter)'." and you'll find many other Java both Swing & SWT apps affected by it. 

The origin is some problem with XULRunner. Some people seem to have "fixed" it by uninstalling it or changing versions, but for me the workaround found e.g. in http://forum.spring.io/forum/spring-projects/springsource-tool-suite/81494-sts-2-3-2-crashes-with-auto-complete-ubuntu-10-04 did the trick, launch like this and it works:

```
  env GRE_HOME=/tmp java -jar TechnicLauncher.jar
```

**Comment by vorburger** [comment] 2014-08-23 21:01
Actually sorry it turns out that this has nothing to do with XULRunner at all .. the GRE_HOME thing doesn't really help, it was a coincidence that it worked for me when writing above - this problem keeps coming and going (i.e. just restarting a few times and crossing fingers eventually helps). I've now been able to isolate this into a standalone example at https://github.com/vorburger/CrashTestDummy, and submitted it as a Java bug report to Oracle.

Note that you can work-around it by using  -Dswing.systemlaf=javax.swing.plaf.nimbus.NimbusLookAndFeel or -Dswing.systemlaf=javax.swing.plaf.metal.MetalLookAndFeel, like this:

```
  java -Dswing.systemlaf=javax.swing.plaf.nimbus.NimbusLookAndFeel -jar TechnicLauncher.jar
```
