### ISSUE TITLE
Tekkit Suddenly very slow

### ISSUE THREAD

**Issue by ShadrachJ** [TechnicPack/TechnicLauncher#456] opened 2014-02-02 16:24 UTC
In tekkitmain i built a magma crucible, and soon afterwards it began to run very slowly, and get stuck at the "building environment" stage of loading a world.  My laptop has 4gb of ram, but the error report seems to show that only 800 are being used. Here is the report: Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 393

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.InstalledPack.loadCachedImage(InstalledPack.java:278)
        net.technicpack.launchercore.install.InstalledPack.loadImage(InstalledPack.java:263)
        net.technicpack.launchercore.install.InstalledPack.getBackground(InstalledPack.java:343)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:128)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:211)
        org.spoutcraft.launcher.skin.ModpackSelector.updatePack(ModpackSelector.java:118)
        net.technicpack.launchercore.install.AvailablePackList.triggerUpdateListeners(AvailablePackList.java:55)
        net.technicpack.launchercore.install.AvailablePackList$3$1.run(AvailablePackList.java:188)
        java.awt.event.InvocationEvent.dispatch(Unknown Source)
        java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.awt.EventQueue.access$200(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.run(Unknown Source)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 127 MB
    Max Memory: 814 MB
    Memory Free: 81 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment] 2014-02-06 08:04
This is a dupe of #432, please offer insights in that task.

**Closed as completed by CannibalVox** 2014-02-06 08:04 UTC
