### ISSUE TITLE
No idea

### ISSUE THREAD

**Issue by KidWithJokes** [TechnicPack/TechnicLauncher#226] opened 2013-03-31 17:28 UTC
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 221

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.technic.rest.RestAPI.shouldUsePatch(RestAPI.java:343)
        org.spoutcraft.launcher.technic.rest.RestAPI.getMinecraftMD5(RestAPI.java:326)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:45)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_17 32 bit
    Total Memory: 33 MB
    Max Memory: 989 MB
    Memory Free: 5 MB
    CPU Cores: 6

**Comment by Salynne** [comment] 2013-03-31 17:38
Duplicate of #212 this should be resolved now. If you restart your launcher it should update to Launcher Build 222

**Closed as completed by Salynne** 2013-03-31 17:38 UTC

**Comment by KidWithJokes** [comment] 2013-03-31 17:42
Only it hasn't
