### ISSUE TITLE
null point

### ISSUE THREAD

**Issue by krdr** [TechnicPack/TechnicLauncher#333] opened 2013-11-23 12:52 UTC
Trying to play the Mod Pack and this happened.

Can you assist please?   

Selected Pack: null
Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:59)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:60)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.6.0_29 64 bit
    Total Memory: 122 MB
    Max Memory: 1816 MB
    Memory Free: 53 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment] 2013-11-24 17:04
Closing this, as it is a duplicate of #326

**Closed as completed by CannibalVox** 2013-11-24 17:04 UTC
