### ISSUE TITLE
Something happened

### ISSUE THREAD

**Issue by abalabahaha** [TechnicPack/TechnicLauncher#338] opened 2013-11-24 00:48 UTC
http://pastebin.com/i3syTQY8

**Comment by CannibalVox** [comment] 2013-11-24 16:29
Can you get me a full log of this incident from .technic/logs?

**Comment by abalabahaha** [comment] 2013-11-24 16:36
Sure, the relevant part from the log is at http://chopapp.com/#6zkz9f3e
I pasted the part up until the crash.

**Comment by CannibalVox** [comment] 2013-11-24 16:38
I need the entire thing, please.

**Comment by abalabahaha** [comment] 2013-11-24 16:47
IT just happened again. http://pastebin.com/fQa0u2cz
Ok entire log at http://chopapp.com/#gusii5ca

**Comment by CannibalVox** [comment] 2013-11-24 16:52
Okay, I've promoted a new version to beta.  Try changing to the beta launcher stream from the cogwheel menu in the top right.  I believe that this beta will replace this crash with a more useful one that I can use to get at the root of the problem.

**Comment by CannibalVox** [comment] 2013-11-24 18:27
Okay, apologies, I had a bug in beta 360, try beta 361. :)

**Comment by abalabahaha** [comment] 2013-11-24 18:33
The problem happens at unknown conditions currently, I will post as soon as the issue pops up again. It may be related to the Immibis Tubestuff Automatic Crafting Table MKII,

**Comment by CannibalVox** [comment] 2013-11-24 18:34
Definitely post any issues you have- I suspect that the fix in 360/361 will change the nature of the crash more or less entirely.

**Comment by abalabahaha** [comment] 2013-11-27 15:31
The issue i saw seems to be fixed.

**Comment by abalabahaha** [comment] 2013-11-27 18:25
Oh no, it just came back:
http://pastebin.com/7C3SDsnk
Forge log: http://chopapp.com/#1j1zapa5

Edit: Description: I opened a TubeStuff Automatic Crafting Table MkII. Then the error appeared.

**Comment by CannibalVox** [comment] 2013-11-27 19:07
Two questions:
1.  Were you in full screen mode when it happened?
2.  Did a zillion error windows open?

**Comment by CannibalVox** [comment] 2013-11-27 19:22
Hello instead of the forge log can you get me the latest launcher log from .technic/logs?  Again, not the forge log.

**Comment by abalabahaha** [comment] 2013-11-27 19:36
1. I was in windowed mode (Not fullscreen mode)
2. Nope. Just one. Your launcher change might have fixed that

Oh sorry, that **was** the launcher log. Not the forge log. Sorry.

**Comment by CannibalVox** [comment] 2013-11-27 19:45
If it's the launcher log, how come it doesn't have the launcher startup message?

**Comment by abalabahaha** [comment] 2013-11-27 19:50
Filtered stuff to prevent the 250+ stalkers and schoolmates from going further, but whatever.
Full log for today: http://chopapp.com/#1wfqcupf

**Comment by CannibalVox** [comment] 2013-11-27 20:14
Quick question: do you have your launcher set up to hide the launcher while minecraft is running?  That is, there are no launcher windows open while minecraft is running, it's just minecraft?

**Comment by abalabahaha** [comment] 2013-11-27 20:16
It hides the launcher frame when Forge starts up, but not the console. I keep the console open for debugging issues.

**Comment by CannibalVox** [comment] 2013-11-27 21:07
Try beta 363, I think the issue is that we were not writing to the console in a thread-safe manner.

**Comment by abalabahaha** [comment] 2013-11-27 23:57
It's hard to reproduce the error, but it relates to the Automatic Crafting Table MkII and opening/closing it...

I will keep you updated

**Comment by CannibalVox** [comment] 2013-12-03 17:05
Closing this- hopefully it's fixed, but please reopen if not.

**Closed as completed by CannibalVox** 2013-12-03 17:05 UTC
