### ISSUE TITLE
Modpack Launching Error

### ISSUE THREAD

**Issue by GodlyPlexi** [TechnicPack/TechnicLauncher#353] opened 2013-11-27 20:47 UTC
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 358

```
Selected Pack: BusinessElite
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.ModpackInstaller.installOldForgeLibs(ModpackInstaller.java:97)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:62)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:60)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.6.0_27 64 bit
    Total Memory: 114 MB
    Max Memory: 1347 MB
    Memory Free: 52 MB
    CPU Cores: 4

I get this error every time I try to start the Business Elite modpack, and it hasn't stopped nor have I found a viable fix for it.

**Comment by CannibalVox** [comment] 2013-11-27 20:47
Duplicate of #352

**Closed as completed by CannibalVox** 2013-11-27 20:47 UTC
