### ISSUE TITLE
Tekkit Lite not loading

### ISSUE THREAD

**Issue by caseyben** [TechnicPack/TechnicLauncher#205] opened 2013-03-22 20:58 UTC
```
Launcher Build: 218
```

---

Stack Trace:
    Exception: EOFException
    Message: null
    Trace:
        java.util.zip.GZIPInputStream.readUByte(Unknown Source)
        java.util.zip.GZIPInputStream.readUShort(Unknown Source)
        java.util.zip.GZIPInputStream.readHeader(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        org.spoutcraft.diff.JBPatch.bspatch(JBPatch.java:94)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.patchMinecraft(MinecraftDownloadUtils.java:62)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:50)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_10 64 bit
    Total Memory: 167 MB
    Max Memory: 1799 MB
    Memory Free: 76 MB
    CPU Cores: 4

**Comment by tpackard7** [comment] 2013-03-22 21:55
I'm having the exact same issue. Does anybody have a fix?
This message occurs after clicking the launch button and it loads the minecraft.jar to 99% and results in a crash.

**Comment by Salynne** [comment] 2013-03-23 13:37
Duplicate of #202

**Closed as completed by Salynne** 2013-03-23 13:37 UTC
