### ISSUE TITLE
Launcher won't download assets such as sounds and records

### ISSUE THREAD

**Issue by Lapito** [TechnicPack/TechnicLauncher#400] opened 2013-12-19 12:17 UTC
Hello. The laucher won't download any assets like it did when it was in beta. It only download modpacks, so the people that don't have the assets don't have sounds too.

**Comment by CannibalVox** [comment] 2013-12-24 06:43
Sorry I know I've been slacking on this, but this is a dupe of #384.

**Closed as completed by CannibalVox** 2013-12-24 06:43 UTC
