### ISSUE TITLE
Technic Launcher Crash

### ISSUE THREAD

**Issue by boristhefriendlyspider** [TechnicPack/TechnicLauncher#488] opened 2014-02-10 18:31 UTC
http://pastebin.com/tug60Kwp

**Comment by git-commit** [comment] 2014-02-10 18:34
Duplicate of #486

**Comment by CannibalVox** [comment] 2014-02-10 18:37
I've rolled out an emergency fix for this.  For now, it still won't let you log in until we can get confirmation from mojang what the hell a null response means.

**Closed as completed by CannibalVox** 2014-02-10 18:37 UTC
