### ISSUE TITLE
Never works

### ISSUE THREAD

**Issue by Danielkeynagy** [TechnicPack/TechnicLauncher#406] opened 2013-12-23 14:38 UTC
keeps saying minecraft isn't installed although it is. can't use any packs because of this

Text:
Stack Trace:
    Exception: RuntimeException
    Message: Minecraft not installed for this pack: InstalledPack{info=SolderPackInfo{name='tekkit', display_name='Tekkit Classic', url='http://www.technicpack.net/tekkit-classic', icon_md5='1db1857730e6e58158ed42dbd5273c0a', logo_md5='45327ab578e28fcddee983922108c268', background_md5='e1f9bda8135b041398f388fa23248d70', recommended='3.1.2', latest='3.1.3', builds=[3.1.3, 3.1.2, 3.1.1, 3.1.0, 3.0.5, 3.0.3, 3.0.2, 3.0.1, 3.0.0], solder=net.technicpack.launchercore.restful.solder.Solder@4ae23d66}, name='tekkit', platform=false, build='recommended', directory='%MODPACKS%\tekkit'}
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:174)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

**Comment by CannibalVox** [comment] 2013-12-24 06:48
This is a dupe of #395, please post your info there.

**Closed as completed by CannibalVox** 2013-12-24 06:48 UTC
