### ISSUE TITLE
Constantly getting crash reports

### ISSUE THREAD

**Issue by Jamesp55** [TechnicPack/TechnicLauncher#329] opened 2013-11-22 23:42 UTC
This is pretty much constant and its doin me head in

2013/11/21 18:55:16 [INFO] Technic Launcher is starting....
2013/11/21 18:55:16 [INFO] Launcher Build: 354
2013/11/21 18:55:16 [INFO] ------------ Startup Parameters ------------
2013/11/21 18:55:16 [INFO] --------- End of Startup Parameters ---------
2013/11/21 18:55:18 [INFO] Analytics Response [runLauncher]: 200
2013/11/21 18:55:18 [SEVERE] Unhandled Exception in Thread[AWT-EventQueue-0,6,main]
java.lang.ArrayIndexOutOfBoundsException: 1
    at javax.swing.text.BoxView.layoutMinorAxis(BoxView.java:846)
    at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:344)
    at javax.swing.text.BoxView.layout(BoxView.java:708)
    at javax.swing.text.BoxView.setSize(BoxView.java:397)
    at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1714)
    at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:912)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1660)
    at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1332)
    at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
    at java.awt.Container.layout(Container.java:1503)
    at java.awt.Container.doLayout(Container.java:1492)
    at java.awt.Container.validateTree(Container.java:1688)
    at java.awt.Container.validate(Container.java:1623)
    at javax.swing.RepaintManager$2.run(RepaintManager.java:691)
    at javax.swing.RepaintManager$2.run(RepaintManager.java:689)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:688)
    at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1679)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:741)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:711)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:220)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:135)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:123)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:119)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:111)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)
2013/11/21 18:55:18 [SEVERE] java.lang.NullPointerException
2013/11/21 18:55:18 [SEVERE]    at org.spoutcraft.launcher.skin.ErrorDialog.<init>(ErrorDialog.java:72)
2013/11/21 18:55:18 [SEVERE]    at org.spoutcraft.launcher.entrypoint.SpoutcraftLauncher$1.uncaughtException(SpoutcraftLauncher.java:151)
2013/11/21 18:55:18 [SEVERE]    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
2013/11/21 18:55:18 [SEVERE]    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
2013/11/21 18:55:18 [SEVERE]    at java.awt.EventDispatchThread.processException(EventDispatchThread.java:242)
2013/11/21 18:55:18 [SEVERE]    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:234)
2013/11/21 18:55:18 [SEVERE]    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:135)
2013/11/21 18:55:18 [SEVERE]    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:123)
2013/11/21 18:55:18 [SEVERE]    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:119)
2013/11/21 18:55:18 [SEVERE]    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:111)
2013/11/21 18:55:18 [SEVERE]    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)
2013/11/21 18:55:32 [INFO]

**Comment by CannibalVox** [comment] 2013-11-24 17:03
We rolled out a fix in Beta 360 that will help us diagnose this, so please try again.  In the meantime, this issue is a duplicate of #338 so please join us there.

**Closed as completed by CannibalVox** 2013-11-24 17:03 UTC
