### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#815] opened 2014-12-26 01:46 UTC
http://pastebin.com/jwQ2YZCy
Err so... was told to put this here?

**Comment by MyNickIsBetter** [comment] 2014-12-26 18:52
My Technic Launcher  have same problem. The solution is wait :/

**Comment by CannibalVox** [comment] 2014-12-27 08:55
This is fixed now.

**Closed as completed by CannibalVox** 2014-12-27 08:55 UTC

**Comment by MyNickIsBetter** [comment] 2014-12-28 01:17
@CanibbalVox the problem is fixed? What? My Technic Launcher is not fixed, the error continues

**Comment by CannibalVox** [comment] 2014-12-28 09:52
Then you should buy minecraft.
