### ISSUE TITLE
Launcher crash

### ISSUE THREAD

**Issue by jgeekw** [TechnicPack/TechnicLauncher#450] opened 2014-01-30 13:23 UTC
Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.InstalledPack.loadCachedImage(InstalledPack.java:278)
        net.technicpack.launchercore.install.InstalledPack.loadImage(InstalledPack.java:263)
        net.technicpack.launchercore.install.InstalledPack.getLogo(InstalledPack.java:238)
        org.spoutcraft.launcher.skin.components.PackButton.setPack(PackButton.java:72)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:161)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:211)
        org.spoutcraft.launcher.skin.ModpackSelector.updatePack(ModpackSelector.java:118)
        net.technicpack.launchercore.install.AvailablePackList.triggerUpdateListeners(AvailablePackList.java:55)
        net.technicpack.launchercore.install.AvailablePackList$3$1.run(AvailablePackList.java:188)
        java.awt.event.InvocationEvent.dispatch(Unknown Source)
        java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.awt.EventQueue.access$200(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.run(Unknown Source)

**Comment by CannibalVox** [comment] 2014-02-06 08:00
Hi, I'm closing this as a dupe of #432, but you can share your insights and track progress there.

**Closed as completed by CannibalVox** 2014-02-06 08:00 UTC
